### your site title here

# for jekyll serve
livereload: 1
force_polling: 1
incremental: 1

title: Derren Yeoh
subtitle: Freelance Sound Designer | Audio Engineer
tagline: Freelance Sound Designer & Audio Engineer based in Singapore
description: Freelance Sound Designer & Audio Engineer based in Singapore, proficient in Cubase, Pro Tools and Adobe Premiere Pro
author: Derren Yeoh

#baseurl:  #name of GitHub repository
url: "derren-audio.com" #custom url to be used instead of GitHub repository

highlighter: rouge
markdown: kramdown

### Pagination
#paginate: 4
#permalink: /blog/:year/:title/
#paginate_path: /blog/page:num/ 

## Contact variables
email: derren.yeohwj@gmail.com
whatsapp: wa.me/6596718659
telegram: t.me/boxmeow

highlighter: rouge
markdown: kramdown

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-target-blank
